# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AudioHelper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AudioHelper
    
    pod 'StarIO', '2.7.0'
    pod 'StarIO_Extension', '1.14.0'
    pod 'SMCloudServices', '1.5.1'

end
